# Generated by Django 6.0.4 on 2026-04-25 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(choices=[('general', 'General Practice'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopaedics', 'Orthopaedics'), ('paediatrics', 'Paediatrics'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('oncology', 'Oncology'), ('radiology', 'Radiology'), ('surgery', 'Surgery')], max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('available_days', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
